server:
  port: 9090
spring:
  application:
    name: gp
  datasource:
    query: # 数据源1
      driver-class-name: dm.jdbc.driver.DmDriver
      jdbc-url: jdbc:dm://10.58.0.46:5236
      username: gpqzk_cx
      password: UFi*uS7_sG8itf9
    add: # 数据源2
      driver-class-name: dm.jdbc.driver.DmDriver
      jdbc-url: jdbc:dm://10.58.0.46:5236
      username: GP_SZZF_W
      password: itUyfrfJi*uS7_sG8u
logging:
  level:
    com.yh.mfox: debug

netty:
  port: 10167
  host: 10.58.0.92